require("user.plugins")
require("user.keymaps")
require("user.options")
require("user.smoothie")
require("user.cmp")
require("user.nvimtree")
require("user.lsp")
require("user.treesitter")
require("user.fidget")
require("user.vim-slash")
require("user.surround")
require("user.colorscheme")
require("user.dap")
require("user.dap-ui")
require("user.whichkey")
require("user.lualine")
require("user.indentline")
require("user.null-ls")
require("user.dap-virtual-text")
require("user.noice")
require("user.jaq")
require("user.hop")
require("user.enhancedjumps")
require("user.autocmds")
-- require("user.scrollbar")
require("user.neoclip")
require("user.telescope")
require("user.toggleterm")
require("user.neovide")
-- require("user.hlslens")
-- require("user.dadbod")

-- Why
require("nvim-comment-frame").setup({
  keymap = "<C-0>",
  multiline_keymap = "<C-9>",
})
-- vim.api.nvim_exec([[
-- function! NvimYabaiNavigate(yabai_direction, vim_direction)
--     let win_nr_before = winnr()
--     execute("wincmd " . a:vim_direction)
--     if win_nr_before ==# winnr()
--         call system("yabai -m window --focus " . a:yabai_direction)
--     endif
-- endfunction
-- ]], true)
