reload("user.plugins")
reload("user.keymaps")
reload("user.options")
reload("user.cmp")
reload("user.nvimtree")
reload("user.lsp")
reload("user.treesitter")
reload("user.fidget")
reload("user.colorscheme")
reload("user.dap")
-- reload("user.dap-ui")
reload("user.whichkey")
reload("user.lualine")
reload("user.null-ls")
reload("user.enhancedjumps")
reload("user.autocmds")
-- reload("user.telescope")
-- reload("user.toggleterm")
reload("user.neovide")
reload("user.smoothie")

-- local cmp_mappings = require("cmp").mappings
-- lvim.builtin.cmp.mapping["<c-r>"] = cmp_mappings.complete()
