-- local cmp = require("cmp")
-- cmp.setup({
--     mapping = {
--         ["<C-k>"] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 'c' }),
--         ["<C-j>"] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 'c' })
--     }
-- lvim.builtin.cmp.on_config_done = function (cmp)
--     cmp.setup.cmdline(":", {
-- 	mapping = cmp.mapping.preset.cmdline(),
-- 	sources = {
-- 		{ name = "cmdline" },
-- 		{ name = "path" },
-- 	},
-- })
-- end

-- lvim.builtin.illuminate.on_config_done = function()
--     local cmp = require("cmp")
--     cmp.setup.cmdline(":", {
-- 	mapping = cmp.mapping.preset.cmdline(),
-- 	sources = {
-- 		{ name = "cmdline" },
-- 		{ name = "path" },
-- 	},
-- })
-- end

-- cmp.setup.cmdline({ "/", "?" }, {
--   mapping = cmp.mapping.preset.cmdline(),
--   sources = {
--     { name = "buffer" },
--   },
-- })
-- lvim.builtin.cmp.sources
-- cmp.setup({
--     enabled = function()
--         return vim.api.nvim_buf_get_option(0, "buftype") ~= "prompt"
--             or require("cmp_dap").is_dap_buffer()
--     end
-- })

-- cmp.setup.filetype({ "dap-repl", "dapui_watches", "dapui_hover" }, {
--     sources = {
--         { name = "dap" },
--     },
-- })

-- local map = function(mode, bind, action)
--     local opts = { noremap = true, silent = true }
--     vim.keymap.set(mode, bind, action, opts)
-- end
-- map("c", "<C-k>", "<nop>") -- Fix for override
-- map("c", "<C-j>", "<nop>") -- Fix for override
-- map("i", "<C-k>", "<nop>") -- Fix for cmp override
-- map("i", "<C-j>", "<nop>") -- Fix for cmp override
-- lvim.builtin.cmp.mapping["<C-k>"] = cmp.mapping(cmp.mapping.select_prev_item(), { 'i', 'c' })
-- lvim.builtin.cmp.mapping["<C-j>"] = cmp.mapping(cmp.mapping.select_next_item(), { 'i', 'c' })
